branch-defaults:
  default:
    environment: Cameron-dev
global:
  application_name: Cameron
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
